<?php

namespace Walletable\Money\Traits;

use InvalidArgumentException;
use Walletable\Money\Money;

/**
 * This is a generated file. Do not edit it manually!
 *
 * @method static Money AED(int $amount)
 * @method static Money ALL(int $amount)
 * @method static Money AMD(int $amount)
 * @method static Money ANG(int $amount)
 * @method static Money AOA(int $amount)
 * @method static Money ARS(int $amount)
 * @method static Money AUD(int $amount)
 * @method static Money AWG(int $amount)
 * @method static Money AZN(int $amount)
 * @method static Money BAM(int $amount)
 * @method static Money BBD(int $amount)
 * @method static Money BDT(int $amount)
 * @method static Money BGN(int $amount)
 * @method static Money BHD(int $amount)
 * @method static Money BIF(int $amount)
 * @method static Money BMD(int $amount)
 * @method static Money BND(int $amount)
 * @method static Money BOB(int $amount)
 * @method static Money BOV(int $amount)
 * @method static Money BRL(int $amount)
 * @method static Money BSD(int $amount)
 * @method static Money BTN(int $amount)
 * @method static Money BWP(int $amount)
 * @method static Money BYN(int $amount)
 * @method static Money BZD(int $amount)
 * @method static Money CAD(int $amount)
 * @method static Money CDF(int $amount)
 * @method static Money CHE(int $amount)
 * @method static Money CHF(int $amount)
 * @method static Money CHW(int $amount)
 * @method static Money CLF(int $amount)
 * @method static Money CLP(int $amount)
 * @method static Money CNY(int $amount)
 * @method static Money COP(int $amount)
 * @method static Money COU(int $amount)
 * @method static Money CRC(int $amount)
 * @method static Money CUC(int $amount)
 * @method static Money CUP(int $amount)
 * @method static Money CVE(int $amount)
 * @method static Money CZK(int $amount)
 * @method static Money DJF(int $amount)
 * @method static Money DKK(int $amount)
 * @method static Money DOP(int $amount)
 * @method static Money DZD(int $amount)
 * @method static Money EGP(int $amount)
 * @method static Money ERN(int $amount)
 * @method static Money ETB(int $amount)
 * @method static Money EUR(int $amount)
 * @method static Money FJD(int $amount)
 * @method static Money FKP(int $amount)
 * @method static Money GBP(int $amount)
 * @method static Money GEL(int $amount)
 * @method static Money GHS(int $amount)
 * @method static Money GIP(int $amount)
 * @method static Money GMD(int $amount)
 * @method static Money GNF(int $amount)
 * @method static Money GTQ(int $amount)
 * @method static Money GYD(int $amount)
 * @method static Money HKD(int $amount)
 * @method static Money HNL(int $amount)
 * @method static Money HRK(int $amount)
 * @method static Money HTG(int $amount)
 * @method static Money HUF(int $amount)
 * @method static Money IDR(int $amount)
 * @method static Money ILS(int $amount)
 * @method static Money INR(int $amount)
 * @method static Money IQD(int $amount)
 * @method static Money IRR(int $amount)
 * @method static Money ISK(int $amount)
 * @method static Money JMD(int $amount)
 * @method static Money JOD(int $amount)
 * @method static Money JPY(int $amount)
 * @method static Money KES(int $amount)
 * @method static Money KGS(int $amount)
 * @method static Money KHR(int $amount)
 * @method static Money KMF(int $amount)
 * @method static Money KPW(int $amount)
 * @method static Money KRW(int $amount)
 * @method static Money KWD(int $amount)
 * @method static Money KYD(int $amount)
 * @method static Money KZT(int $amount)
 * @method static Money LAK(int $amount)
 * @method static Money LBP(int $amount)
 * @method static Money LKR(int $amount)
 * @method static Money LRD(int $amount)
 * @method static Money LSL(int $amount)
 * @method static Money LYD(int $amount)
 * @method static Money MAD(int $amount)
 * @method static Money MDL(int $amount)
 * @method static Money MGA(int $amount)
 * @method static Money MKD(int $amount)
 * @method static Money MMK(int $amount)
 * @method static Money MNT(int $amount)
 * @method static Money MOP(int $amount)
 * @method static Money MRU(int $amount)
 * @method static Money MUR(int $amount)
 * @method static Money MVR(int $amount)
 * @method static Money MWK(int $amount)
 * @method static Money MXN(int $amount)
 * @method static Money MXV(int $amount)
 * @method static Money MYR(int $amount)
 * @method static Money MZN(int $amount)
 * @method static Money NAD(int $amount)
 * @method static Money NGN(int $amount)
 * @method static Money NIO(int $amount)
 * @method static Money NOK(int $amount)
 * @method static Money NPR(int $amount)
 * @method static Money NZD(int $amount)
 * @method static Money OMR(int $amount)
 * @method static Money PAB(int $amount)
 * @method static Money PEN(int $amount)
 * @method static Money PGK(int $amount)
 * @method static Money PHP(int $amount)
 * @method static Money PKR(int $amount)
 * @method static Money PLN(int $amount)
 * @method static Money PYG(int $amount)
 * @method static Money QAR(int $amount)
 * @method static Money RON(int $amount)
 * @method static Money RSD(int $amount)
 * @method static Money RUB(int $amount)
 * @method static Money RWF(int $amount)
 * @method static Money SAR(int $amount)
 * @method static Money SBD(int $amount)
 * @method static Money SCR(int $amount)
 * @method static Money SDG(int $amount)
 * @method static Money SEK(int $amount)
 * @method static Money SGD(int $amount)
 * @method static Money SHP(int $amount)
 * @method static Money SLL(int $amount)
 * @method static Money SOS(int $amount)
 * @method static Money SRD(int $amount)
 * @method static Money SSP(int $amount)
 * @method static Money STN(int $amount)
 * @method static Money SVC(int $amount)
 * @method static Money SYP(int $amount)
 * @method static Money SZL(int $amount)
 * @method static Money THB(int $amount)
 * @method static Money TJS(int $amount)
 * @method static Money TMT(int $amount)
 * @method static Money TND(int $amount)
 * @method static Money TOP(int $amount)
 * @method static Money TRY(int $amount)
 * @method static Money TTD(int $amount)
 * @method static Money TWD(int $amount)
 * @method static Money TZS(int $amount)
 * @method static Money UAH(int $amount)
 * @method static Money UGX(int $amount)
 * @method static Money USD(int $amount)
 * @method static Money USN(int $amount)
 * @method static Money UYI(int $amount)
 * @method static Money UYU(int $amount)
 * @method static Money UYW(int $amount)
 * @method static Money UZS(int $amount)
 * @method static Money VES(int $amount)
 * @method static Money VND(int $amount)
 * @method static Money VUV(int $amount)
 * @method static Money WST(int $amount)
 * @method static Money XAF(int $amount)
 * @method static Money XAG(int $amount)
 * @method static Money XAU(int $amount)
 * @method static Money XBA(int $amount)
 * @method static Money XBB(int $amount)
 * @method static Money XBC(int $amount)
 * @method static Money XBD(int $amount)
 * @method static Money XBT(int $amount)
 * @method static Money XCD(int $amount)
 * @method static Money XDR(int $amount)
 * @method static Money XOF(int $amount)
 * @method static Money XPD(int $amount)
 * @method static Money XPF(int $amount)
 * @method static Money XPT(int $amount)
 * @method static Money XSU(int $amount)
 * @method static Money XTS(int $amount)
 * @method static Money XUA(int $amount)
 * @method static Money XXX(int $amount)
 * @method static Money YER(int $amount)
 * @method static Money ZAR(int $amount)
 * @method static Money ZMW(int $amount)
 * @method static Money ZWL(int $amount)
 * @psalm-immutable
 */
trait MoneyFactory
{
    /**
     * Convenience factory method for a Money object.
     *
     * @param string          $method
     * @param array{int=>mixed} $arguments
     *
     * @throws InvalidArgumentException If amount is not integer(ish).
     *
     * @psalm-pure
     */
    public static function __callStatic(string $method, array $arguments): Money
    {
        return new Money($arguments[0], Money::currency($method));
    }
}
